name: Arch Linux

on:
  push:
    branches: [ archlinux ]
    tags:
      - 'v*'
      - '*.*.*'
  pull_request:
    branches: [ archlinux ]

permissions:
  contents: write

jobs:
  build-arch:
    runs-on: ubuntu-latest
    container: archlinux:latest
    
    steps:
    - name: Update Arch and install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm --needed \
          git base-devel clang \
          gtk3 libnotify openssl freetype2 \
          libx11 libxinerama libxrender libxft \
          libxdmcp fontconfig libxcb libxext \
          gdk-pixbuf2 zlib harfbuzz pango \
          atk cairo glib2 libpng
        
    - name: Checkout Bobcat repository
      uses: actions/checkout@v4
      with:
        path: Bobcat
        fetch-depth: 0
        
    - name: Checkout U++ repository
      uses: actions/checkout@v4
      with:
        repository: ultimatepp/ultimatepp
        ref: v2025.1.1
        path: upp-source
        
    - name: Configure and build U++ from the master branch
      working-directory: upp-source
      run: |
        ./configure
        make -f ./umkMakefile -j 4
        
    - name: Build Bobcat
      working-directory: Bobcat
      run: ../upp-source/umk ./,../upp-source/uppsrc Bobcat CLANG.bm -brh +GUI,SHARED bobcat
      
    - name: Get the version
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "VERSION=0.9.7" >> $GITHUB_ENV
      shell: bash
        
    - name: Create Arch Linux package
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        # Create PKGBUILD
        cat <<EOF > PKGBUILD
        pkgname=bobcat-terminal
        pkgver=${{ env.VERSION }}
        pkgrel=1
        pkgdesc="A powerful yet user-friendly, cross platform terminal emulator"
        arch=('x86_64')
        url="https://github.com/ismail-yilmaz/bobcat"
        license=('custom')
        depends=(
        gtk3 libnotify openssl freetype2
        libx11 libxinerama libxrender libxft
        libxdmcp fontconfig libxcb libxext
        gdk-pixbuf2 zlib harfbuzz pango
        atk cairo glib2 libpng
        )
        source=("bobcat-\$pkgver.tar.gz")
        sha256sums=('SKIP')

        package() {
        cd "\$srcdir/bobcat-\$pkgver"
  
        install -Dm755 bobcat "\$pkgdir/usr/bin/bobcat"
        install -Dm644 Bobcat/data/bobcat.desktop "\$pkgdir/usr/share/applications/bobcat.desktop"
        install -Dm644 Bobcat/data/bobcat128x128.png "\$pkgdir/usr/share/pixmaps/bobcat.png"
        install -Dm644 Bobcat/Copying "\$pkgdir/usr/share/licenses/\$pkgname/LICENSE"
        }
        EOF
        
        # Create source tarball and build package
        tar czf bobcat-${{ env.VERSION }}.tar.gz Bobcat/
        makepkg -s --noconfirm
        
    - name: Upload Arch package as artifact
      #if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-artifact@v4
      with:
        name: bobcat-terminal_${{ env.VERSION }}_arch_amd64
        path: bobcat-*.pkg.tar.zst
