name: Windows

on:
  push:
    branches: [ windows_build ]
  pull_request:
    branches: [ windows_build ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout Bobcat repository
      uses: actions/checkout@v3
      with:
        path: Bobcat

    - name: Download U++ Windows Release
      run: |
        Invoke-WebRequest -Uri "https://www.ultimatepp.org/downloads/upp-win-17490.7z" -OutFile "upp-win.7z"

    - name: Extract U++ Release
      run: |
        7z x upp-win.7z -oupp-source

    - name: Add missing mingit path
      working-directory: upp-source
      run: |
        $gitPath = Resolve-Path -Path ".\bin\mingit\cmd" # Temporary workaround for umk's missing mingit path.
        $env:PATH += $gitPath.path

    - name: Build Bobcat
      working-directory: Bobcat
      run: |
        $umkPath = Get-ChildItem -Path ..\upp-source -Recurse -Filter 'umk.exe' | Select-Object -First 1 -ExpandProperty FullName
        & $umkPath .\,"..\upp-source\uppsrc" Bobcat CLANGx64.bm -brh +GUI,WIN64, WIN10 bobcat
